name: example
description: A simple example app for the sliding_up_panel package.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.3.2"

dependencies:
  flutter:
    sdk: flutter

  sliding_up_panel:
    path: ../

  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  cached_network_image: ^3.3.1

  cupertino_icons: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true